spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=closerShareLocation;encrypt=true;trustServerCertificate=true;
    username: ducan
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        "[format_sql]": false
    database-platform: org.hibernate.dialect.SQLServerDialect
application:
  security:
    jwt:
      secret-key: ZjQ0MzYxZjE0MzUyMmI3ZjU1YzE5NjQwY2I0ZjU2YmUwNzE4M2QxZjg4ZDk1NzJiMmQxNzg0MDk5M2I3N2QyZDk5YmE0YmJlOTc3YmIyODA4NDk3NzQwMjA4MDIyZTc4YjE1MTc5M2RiNzg3MjBhZTc1OTRlMTUwODFhZDkxY2I0ODFhMmIwNGJiNTJlNTFhN2UxOTg1MDk3ZDQyOGUwYzE0NDg4MDA5NzA5MjRiOWQyYmQxMTVlNDk1OWI0NGEwMDc3ZDkxODc5NTg4NDUwYjRlMzBhN2FhNmJiOGU1MTBhMTA4YTJiNTJlODkxNzE0MDA3NmRiOTg3OTQyMmVlZWVhOWE5ZTc4ODIyNDg=
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
